.TH "md__r_e_a_d_m_e" 3 "Thu Feb 7 2019" "Version 0.1.0" "UTFC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- UTFC a UTF-8 library for C 
The api is documented in the code and in the docs folder\&. ## Usage example 
.PP
.nf
#include <utfc\&.h>
void main() {
    
}

.fi
.PP
 
.SS "Licensing"
.PP
Copyright (c) 2019 Delta Foundry All rights reserved\&. 
.br
Usage and redistribution permitted as per the terms laid in the LICENSE file\&. 
