.TH "utf8_codepoint__" 3 "Thu Feb 7 2019" "Version 0.1.0" "UTFC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8_codepoint__
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "byte \fBbytes\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for UTFC from the source code\&.
